name: Yarn Cache

# description: | #markdown
#   Similar idea to the yarn-cache action, but makes sure that only one workflow
#   can create the cache at a time. EG:

#   ```yaml
#   jobs:
#     cache:
#       uses: johngeorgewright/workflows/workflows/yarn-cache@main
#     test:
#       needs: [cache]
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/checkout@v6
#
#         # OPTION 1: manually download the cache
#         - uses: actions/cache/restore@v5
#           with:
#             key: ${\{ needs.cache.outputs.key }}
#             path: ${\{ needs.cache.outputs.path }}
#             restore-keys: ${\{ needs.cache.outputs.restore-keys }}
#
#         # OPTION 2: let the key be discovered automatically
#         - uses: actions/setup-node@v6
#         - uses: johngeorgewright/workflows/actions/yarn-cache@main
#     ```

on:
  workflow_call:
    inputs:
      cache-path:
        description: The cache paths
        required: false
        type: string
        default: |
          ~/.cache
          .yarn/unplugged
          .yarn/install-state.gz

      runs-on:
        default: ubuntu-latest
        required: false
        type: string
        description: Use runs-on to define the type of machine to run the job on.

      working-directory:
        description: Optional directory to execute yarn command in
        required: false
        type: string
        default: ${{ github.workspace }}

    outputs:
      key:
        value: ${{ jobs.key.outputs.cache-key }}
      path:
        value: ${{ jobs.prime.outputs.cache-path }}
      restore-keys:
        value: ${{ jobs.key.outputs.cache-restore-keys }}

jobs:
  key:
    name: Key
    runs-on: ${{ inputs.runs-on }}
    outputs:
      cache-key: ${{ steps.key.outputs.cache-key }}
      cache-restore-keys: ${{ steps.key.outputs.cache-restore-keys }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Install Node.js
        id: node
        uses: actions/setup-node@v6
        with:
          node-version-file: ${{ inputs.working-directory }}/.nvmrc

      - run: corepack enable

      - name: Key
        id: key
        uses: johngeorgewright/workflows/actions/yarn-cache-key@yarn-cache
        with:
          working-directory: ${{ inputs.working-directory }}

  prime:
    name: Prime
    needs: [key]
    runs-on: ${{ inputs.runs-on }}
    concurrency:
      group: ${{ needs.key.outputs.cache-key }}
    outputs:
      cache-path: ${{ inputs.cache-path }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ${{ inputs.working-directory }}/.nvmrc

      - run: corepack enable

      - uses: johngeorgewright/workflows/actions/yarn-cache@yarn-cache
        with:
          cache-path: ${{ inputs.cache-path }}
          working-directory: ${{ inputs.working-directory }}
